spring:
  application:
    name: paradox
  datasource:
    url: jdbc:postgresql://localhost:5432/paradox_db
    username: amixady
    password: amixady
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080


jwt:
  secret: "mY5tr0nG@nd$3cureJWTs3cr3tKey1234567890!@#"
  access-token-expiration-ms: 3600000
  refresh-token-expiration-ms: 86400000





